#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

sudo pkg update &&
    sudo pkg install -y python3 ca_root_nss &&
    sudo pkg clean -y &&
    sudo python3 -m ensurepip &&
    sudo pip3 install --upgrade pip
